<?php 
$settings = array(	
	array(
		'title' => __( 'Cart CSS Options', 'woocommerce-custom-settings-plugin' ),
		'type'  => 'title',
		'desc'  => '',
		'id'    => 'cart_css_options',
	),		
	array(
		'title'    => __( 'Table Border Size', 'woocommerce-custom-settings-plugin' ),
		'desc'     => __( 'Select table border size for the cart page. The defalut color added by the WooCommerce CSS.', 'woocommerce-custom-settings-plugin' ),
		'id'       => 'table_border_size',
		'type'     => 'ms_size',
		'css'      => 'width:4em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),			
	array(
		'title'    => __( 'Table Border Color', 'woocommerce-custom-settings-plugin' ),
		'desc'     => __( 'Select color for buttons background color. The defalut color added by the WooCommerce CSS.', 'woocommerce-custom-settings-plugin' ),
		'id'       => 'table_bor_clr',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '#000000',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Table Heading Background Color', 'woocommerce-custom-settings-plugin' ),
		'desc'     => __( 'Select color for table heading background color. The defalut color added by the WooCommerce CSS.', 'woocommerce-custom-settings-plugin' ),
		'id'       => 'table_hbg_clr',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '#000000',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Table Heading Text Color', 'woocommerce-custom-settings-plugin' ),
		'desc'     => __( 'Select color for the cart table heading text color. The defalut color added by the WooCommerce CSS.', 'woocommerce-custom-settings-plugin' ),
		'id'       => 'table_htext_clr',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '#000000',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Table Text Color', 'woocommerce-custom-settings-plugin' ),
		'desc'     => __( 'Select color for the cart table text color. The defalut color added by the WooCommerce CSS.', 'woocommerce-custom-settings-plugin' ),
		'id'       => 'table_text_clr',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '#000000',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'type' => 'sectionend',
		'id'   => 'cart_css_options',
	),
);