<?php
$settings = array(
    array(
        'title' => __('Shop Page Category Loop CSS', 'woocommerce-custom-settings-plugin') ,
        'type' => 'title',
        'desc' => '',
        'id' => 'shop_cat_css_options',
    ) ,
	array(
        'title' => __('Category Title Font Family', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Add here the Category text Font family CSS. Black set default from body.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'cat_text_ff',
        'type' => 'text',
        'css' => 'width:20em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ),
    array(
        'title' => __('Category Title Color', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select product title color here.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'cat_title_clr',
        'type' => 'color',
        'css' => 'width:6em;',
        'default' => '#000000',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
    array(
        'title' => __('Category Title Size', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select product title size in pixles.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'cat_title_size',
        'type' => 'ms_size',
        'css' => 'width:4em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
	array(
        'title' => __('Category Title Font Weight', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Add here the Category Title Font Weight CSS.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'cat_title_fw',
        'type' => 'text',
        'css' => 'width:10em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ),
	array(
        'title' => __('Category Box Padding', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select Category box padding', 'woocommerce-custom-settings-plugin') ,
        'id' => 'cat_box_pading',
        'type' => 'ms_dimension',
        'css' => 'width:4em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
    array(
        'title' => __('Category Box Border', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select Category box border size in pixles.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'cat_box_bor',
        'type' => 'ms_border',
        'css' => 'width:4em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
    array(
        'title' => __('Category Box  Radius', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select Category box border radius in %', 'woocommerce-custom-settings-plugin') ,
        'id' => 'cat_box_bor_radis',
        'type' => 'ms_dimension',
        'css' => 'width:4em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
    array(
        'title' => __('Category Box Shadow', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Add here the Category box shadow CSS.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'cat_box_shadow',
        'type' => 'text',
        'css' => 'width:20em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ),
    array(
        'type' => 'sectionend',
        'id' => 'shop_cat_css_options',
    ) ,
	array(
        'title' => __('Shop Page Product Loop CSS', 'woocommerce-custom-settings-plugin') ,
        'type' => 'title',
        'desc' => '',
        'id' => 'shop_product_css_options',
    ) ,
	array(
        'title' => __('Product Title Font Family', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Add here the Product text Font family CSS. Black set default from body.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'product_text_ff',
        'type' => 'text',
        'css' => 'width:20em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ),
    array(
        'title' => __('Product Title Color', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select product title color here.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'product_title_text',
        'type' => 'color',
        'css' => 'width:6em;',
        'default' => '#000000',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
    array(
        'title' => __('Product Title Size', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select product title size in pixles.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'product_title_size',
        'type' => 'ms_size',
        'css' => 'width:4em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
	array(
        'title' => __('Product Title Font Weight', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Add here the Product Title Font Weight CSS.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'product_title_fw',
        'type' => 'text',
        'css' => 'width:10em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ),
    array(
        'title' => __('Product Price Color', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select product title color here.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'product_price_text',
        'type' => 'color',
        'css' => 'width:6em;',
        'default' => '#000000',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
    array(
        'title' => __('Product Price Size', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select product price size in pixles.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'product_price_size',
        'type' => 'ms_size',
        'css' => 'width:4em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
	array(
        'title' => __('Product Price Font Weight', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Add here the Product Price Font Weight CSS.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'product_price_fw',
        'type' => 'text',
        'css' => 'width:10em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ),
	array(
        'title' => __('Product Box Padding', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select product box padding', 'woocommerce-custom-settings-plugin') ,
        'id' => 'product_box_pading',
        'type' => 'ms_dimension',
        'css' => 'width:4em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
    array(
        'title' => __('Product Box Border', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select product box border size in pixles.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'product_box_bor',
        'type' => 'ms_border',
        'css' => 'width:4em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
    array(
        'title' => __('Product Box Border Radius', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select product box border radius in %', 'woocommerce-custom-settings-plugin') ,
        'id' => 'product_box_bor_radis',
        'type' => 'ms_dimension',
        'css' => 'width:4em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
    array(
        'title' => __('Product Box Shadow', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Add here the product box shadow CSS.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'product_box_shadow',
        'type' => 'text',
        'css' => 'width:20em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ),
    array(
        'type' => 'sectionend',
        'id' => 'shop_product_css_options',
    ) ,    
    array(
        'title' => __('Webiste Product Buttons CSS', 'woocommerce-custom-settings-plugin') ,
        'type' => 'title',
        'desc' => '',
        'id' => 'btn_css_options',
    ),
	array(
        'title' => __('Button Font Family', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Add here the Category text Font family CSS. Black set default from body.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'btn_text_ff',
        'type' => 'text',
        'css' => 'width:20em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ),
	array(
        'title' => __('Button Font Size', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select font size in Pixels of the product cart button.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'btn_font_size',
        'type' => 'ms_size',
        'css' => 'width:4em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ),
	array(
        'title' => __('Button Font Weight', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Add here the Button Font Weight CSS.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'btn_title_fw',
        'type' => 'text',
        'css' => 'width:10em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ),
    array(
        'title' => __('Button Background Color', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select color for buttons background color. The defalut color added by the WooCommerce CSS.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'btn_clr',
        'type' => 'color',
        'css' => 'width:6em;',
        'default' => '#3c3c3c',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
    array(
        'title' => __('Button Text Color', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select color for buttons background color. The defalut color added by the WooCommerce CSS.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'btn_txt_clr',
        'type' => 'color',
        'css' => 'width:6em;',
        'default' => '#3c3c3c',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
    array(
        'title' => __('Button Hover Background Color', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select color for buttons hover background color. The defalut color added by the WooCommerce CSS.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'btn_hclr',
        'type' => 'color',
        'css' => 'width:6em;',
        'default' => '#3c3c3c',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
    array(
        'title' => __('Button Hover Text Color', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select color for buttons hover background color. The defalut color added by the WooCommerce CSS.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'btn_htxt_clr',
        'type' => 'color',
        'css' => 'width:6em;',
        'default' => '#3c3c3c',
        'autoload' => false,
        'desc_tip' => true,
    ) ,    
    array(
        'title' => __('Button Padding', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select product button Padding', 'woocommerce-custom-settings-plugin') ,
        'id' => 'product_btn_padding',
        'type' => 'ms_dimension',
        'css' => 'width:4em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
    array(
        'title' => __('Button Border Radius', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select button border radius in Pixels', 'woocommerce-custom-settings-plugin') ,
        'id' => 'btn_bor_radius',
        'type' => 'ms_dimension',
        'css' => 'width:4em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
    array(
        'type' => 'sectionend',
        'id' => 'btn_css_options',
    ),
	array(
        'title' => __('Product detail Page CSS', 'woocommerce-custom-settings-plugin') ,
        'type' => 'title',
        'desc' => '',
        'id' => 'pro_detail_css_options',
    ),
	array(
        'title' => __('Product Title Font Family', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Add here the Product details page text Font family CSS. Black set default from body.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'pro_detail_text_ff',
        'type' => 'text',
        'css' => 'width:20em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ),
    array(
        'title' => __('Product Title Color', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select product title color here.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'pro_detail_title_text',
        'type' => 'color',
        'css' => 'width:6em;',
        'default' => '#000000',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
    array(
        'title' => __('Product Title Size', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select product title size in pixles.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'pro_detail_title_size',
        'type' => 'ms_size',
        'css' => 'width:4em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
	array(
        'title' => __('Product Title Font Weight', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Add here the Product Title Font Weight CSS.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'pro_detail_title_fw',
        'type' => 'text',
        'css' => 'width:10em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ),
    array(
        'title' => __('Product Price Color', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select product title color here.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'pro_detail_price_text',
        'type' => 'color',
        'css' => 'width:6em;',
        'default' => '#000000',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
    array(
        'title' => __('Product Price Size', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Select product price size in pixles.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'pro_detail_price_size',
        'type' => 'ms_size',
        'css' => 'width:4em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ) ,
	array(
        'title' => __('Product Price Font Weight', 'woocommerce-custom-settings-plugin') ,
        'desc' => __('Add here the Product Price Font Weight CSS.', 'woocommerce-custom-settings-plugin') ,
        'id' => 'pro_detail_price_fw',
        'type' => 'text',
        'css' => 'width:10em;',
        'default' => '',
        'autoload' => false,
        'desc_tip' => true,
    ),
    array(
        'type' => 'sectionend',
        'id' => 'pro_detail_css_options',
    ),
);

